### ISSUE TITLE
have POST /api/courses/<slug>/roster/ expect a csv file and...

### ISSUE THREAD

**Issue by hcientist** [JMU-CIME/CPR-Music-Backend#5]
add student enrollments for each entry in CSV (first creating user for student if necessary) and respond with all enrollments for this course (or maybe just the newly created ones?)

**Comment by nwself** [comment]
Done https://github.com/JMU-CIME/CPR-Music-Backend/blob/main/docs/api.md#post-apicoursesslugroster
