### ISSUE TITLE
Bug or just me?

### ISSUE THREAD

**Issue by hcientist** [JMU-CIME/CPR-Music-Backend#6]
https://github.com/JMU-CIME/CPR-Music-Backend/blob/1e43fdd45158a3039105666b7362faba65421b9f/teleband/courses/api/views.py#L113

is the get here a bug or did I just do something weird (like artificially have 2 courses with the same slug? 🤔)

**Comment by nwself** [comment]
What bug did you see? This like should get every Enrollment related to this course.

**Comment by hcientist** [comment]
I got a throw on the get_object, i'm betting it's bc i sort of bypassed django in having 2 courses with the same slug? so maybe no bug here?

**Comment by nwself** [comment]
Yes, if you have two courses with the same slug `get_object` here will definitely throw and say something like "get didn't get 1 object - it got 2!"

**Comment by nwself** [comment]
Closing as "just you" 😛
